export { default as Introduction } from "./Introduction"
export { default as HeroSection } from "./HeroSection"
export { default as FaqSection } from "./FaqSection"
export { default as QuestioniareSection } from "./QuestioniareSection"
export { default as SkillsSection } from "./SkillsSection"